name: iml-voice-recognition
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - jupyterlab
  - tensorboard
  - pip:
    - pre-commit
